### ISSUE TITLE
Will no longer be updated to the Raku ecosystem

### ISSUE THREAD

**Issue by lizmat** [YellowApple/p6-GLFW#4]
Hello,

Thank you for the time and effort you have put in what is now the [Raku Programming Language](https://raku.org).  The language and its ecosystem are [moving forward](https://github.com/Raku/problem-solving/pull/318).

This means that this distribution will no longer be checked for updates by the Raku ecosystem.

This means that you will need to move your module to the [zef ecosystem](https://deathbykeystroke.com/articles/20210120-faq-zef-ecosystem.html) on the next update you make to these distributions.  Otherwise your update will simply not be seen by the ecosystem.

If you are no longer interested in maintaining this distribution, you can have this distribution moved to [Raku Community Modules Adoption Center](https://github.com/raku-community-modules/), where members of the Raku Community will take care of them.

This can be as easy as confirming that in a response to this issue.

Again, thank you for your time and efforts!

On behalf of the Raku Steering Council,

Elizabeth Mattijsen

**Comment by YellowApple** [comment]
Howdy Elizabeth!  Thanks for the heads up.

Just to clarify my understanding:

- For the current (and previous) version of this distribution, no action is needed, since `GLFW:ver<0.1.0>` is [already indexed](https://raku.land/github:YellowApple/GLFW)
- For future versions of this distribution, I'll need to setup `fez` and use that to upload said future versions

Is that correct?  Or am I misunderstanding?

**Comment by lizmat** [comment]
> For future versions of this distribution, I'll need to setup fez and use that to upload said future versions

That is correct.

**Comment by YellowApple** [comment]
Version 0.1.1 released and published via `fez`, so going forward we should be good to go.  Thanks!

**Comment by lizmat** [comment]
Thanks for the upload to zef ecosystem.  Closing now.
